name: Create Branch
description: 'Create Branch to trigger CodeBuild deploy'
inputs:
  branch-name:
    description: 'The name of the new branch'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Branch
      run: |
        git push origin --delete ${{ github.event.inputs.branch-name }}
        git branch ${{ github.event.inputs.branch-name }}
        git push origin ${{ github.event.inputs.branch-name }}
      shell: bash