name: Create Branch
description: 'Create Branch to trigger CodeBuild deploy'
inputs:
  branch-name:
    description: 'The name of the new branch'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Branch
      if: always()
      run: |
        git push origin --delete ${{ inputs.branch-name }}
        git branch ${{ inputs.branch-name }}
        git push origin ${{ inputs.branch-name }}
      shell: bash