name: Stag Deploy Flow

on: workflow_dispatch

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Create new branch
        uses: ./.github/actions/create-branch
        with:
          branch-name: "deploy/stag/global/common/all/plan"